### ISSUE TITLE
Make the Internet Explorer to actually function

### ISSUE THREAD

**Issue by pkgamma** [ShizukuIchi/winXP#12]
I would like for the Internet Explorer to actually function so I can browse websites in this virtual "Windows XP" environment. With that, I will actually be able to prank my friends and say that I am operating Windows XP. I can create a pull request for it as well when I have time. Thanks.

![bitmoji](https://render.bitstrips.com/v2/cpanel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-b76f340d-238d-4da6-933a-e1e79142901b-v1.png?transparent=1&palette=1&width=246)

**Comment by ShizukuIchi** [comment]
Hi @pkgamma! I thought about this before but not everything can be "iframed" due to X-Frame-Options

**Comment by captbaritone** [comment]
I thought about this for Webamp. Did you know Winamp had a browser window? One other thing that I don’t think is possible, is having a functioning back button that exists outside the frame.

**Comment by pkgamma** [comment]
True, there are probably going to be a lot of barriers trying to implement this. There is actually already a discussion about this [on Reddit](https://www.reddit.com/r/webdev/comments/b6ihor/windows_xp_in_react/ejkqiir?utm_source=share&utm_medium=web2x), and they can't seem to find an easy workaround. Because of that, I should probably just close the issue. I am hoping though to see more software added, for example, the awesome [Webamp](https://webamp.org/) from @captbaritone.

**Comment by RonnyO** [comment]
I'd like to add that when @altryne developed his [Web iPad Simulator](https://alexw.me/ipad2/) he also made traffic go through a proxy with the appropriate UA string, which is super cool (in this case, make websites think this is IE6), but that led to a block by Google since they don't like such proxies for security and privacy reasons.

So it's a shame, but other than maybe having some other fake websites for things saved in the fake bookmarks, I don't think this IE6 would/could become usable.
