### ISSUE TITLE
Use iframes for internet explorer

### ISSUE THREAD

**Issue by rauchg** [ShizukuIchi/winXP#48]
Which would allow you to introduce `winxp.now.sh` in the URL bar and load itself.

**Comment by ShizukuIchi** [comment]
Hi @rauchg! This [has been brought up before](https://github.com/ShizukuIchi/winXP/issues/12) but I can't find a good solution. Do you have any idea?

**Comment by ghostslayer989** [comment]
https://www.npmjs.com/package/react-iframe

**Comment by padraigfl** [comment]
Just adding what I know from trying to figure this stuff out myself...

Due to cross origin restrictions with iframes, the experience of just bolting them in here would be pretty horrible and crappy looking.

What can be done is:
- Displays webpages in an extremely restrictive manner (e.g. disable scrolling so you don't have to deal with the scrollbar style clashes)
- Design an iframe handler exclusively for pages coming from the same origin. Following a simple validation check (i.e. that you can access the window's properties), you have pretty much full control of what's going on within the iframe so you can set the window size to be the size of the iframe content and handle overflows in the component itself.


I'm trying the latter one atm on my similar thing, might be able to give some further ideas in a week or two.
